# Generated by Django 5.0.6 on 2024-06-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.AutoField(db_column='idJuego', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('desarrollador', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('resena', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.CharField(max_length=10)),
                ('editor', models.CharField(max_length=50)),
            ],
        ),
    ]
