# Generated by Django 5.0.6 on 2024-06-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam3Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='ruta_imagen',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
