# Generated by Django 5.0.6 on 2024-06-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam3Proyecto', '0002_juego_genero_juego_ruta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
