# Generated by Django 5.0.6 on 2024-06-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam3Proyecto', '0003_juego_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.CharField(max_length=100),
        ),
    ]
