# Generated by Django 5.0.6 on 2024-07-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam3Proyecto', '0004_alter_juego_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('Usuario', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
