# Generated by Django 5.0.6 on 2024-07-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steam3Proyecto', '0007_alter_compra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
